Ebihara dev
mitsuyukiLab/tpg-ship-sim pull request #6
Opened 2024-06-02 11:01 UTC by ebihara302

storage_baseの変更を元にtpg_shipとsupport_shipを変更してみました。
あと、発表スライド等では台風進路予報のモデルを入力モデルとしているので、それに合わせてforecasterもconfigファイルで変更できるようにしました。tpg_shipについても性能モデルと運用規則モデルの変更を行えるようにしました。

2024-06-03 04:05 UTC, taiga4112 requested changes
@ebihara302 
少しコメントしました。適宜修正してまた再度PRを送ってください

2024-06-03 04:05 UTC, taiga4112 commented on conf/config.yaml
> +  year: 2019
あるべき姿を考えると、この'year'、いらないです。

2024-06-03 04:05 UTC, taiga4112 commented on main.py
>      st_base = storage_base.storage_BASE(base_locate, st_base_max_storage_wh)
storage_BASEの大文字が気持ち悪いから、今のうちに修正しときましょうか。

2024-06-03 04:05 UTC, taiga4112 commented on main.py
> +    support_ship_1 = support_ship.support_SHIP(
こちらもSHIPの大文字が気持ち悪いので修正ですね。

2024-06-03 04:05 UTC, taiga4112 commented on main.py
> +    support_ship_2 = support_ship.support_SHIP(
こちらもSHIPの大文字が気持ち悪いので修正ですね。

2024-06-04 03:43 UTC, ebihara302 commented on main.py
>      st_base = storage_base.storage_BASE(base_locate, st_base_max_storage_wh)
Storage_baseとしました。クラスは頭文字だけ大文字にして一応区別することにしました。

2024-06-04 03:43 UTC, ebihara302 commented on main.py
> +    support_ship_1 = support_ship.support_SHIP(
Support_shipとしました。クラスは頭文字だけ大文字にして一応区別することにしました。

2024-06-04 03:43 UTC, ebihara302 commented on main.py
> +    support_ship_2 = support_ship.support_SHIP(
Support_shipとしました。クラスは頭文字だけ大文字にして一応区別することにしました。

2024-06-04 03:46 UTC, ebihara302 commented on conf/config.yaml
> +  year: 2019
了解です。削除しました。
ただ、現状のシミュレータのデータにおいては台風進路データのパスの年数とシミュレータに入力した年数がズレるとエラーになるのでできれば一括で確認できるようにしておきたかったという考えもありました。（あと、パラメータ探索時に年の変更が簡単にできなさそうな気がしたので、一応追加していました。）

2024-06-04 03:50 UTC, ebihara302 commented on conf/config.yaml
> +  sub_judge_energy_storage_per: 40 # 蓄電量がこの値を下回ると寄港判断を行う[%]
judge_energy_storage_perに関しては確かに100％で良いと思いましたのでconfigから削除しました。
sub_judge_energy_storage_perについてはそれに伴って、govia_base_judge_energy_storage_perに名前を変更しました。寄港をとりあえずgo via baseと表記しています。

2024-06-04 03:50 UTC, ebihara302 commented on conf/config.yaml
> +  first_locate: [24, 153] # lat, lon
修正しました。

2024-06-04 06:40 UTC, ebihara302 reviewed
コメントに応じて修正したものです。

2024-06-04 06:41 UTC, closed without merging